# Generated by Django 4.1.7 on 2023-03-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='feature',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='habitat',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='locations',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='scientific_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='slogan',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
