# Generated by Django 4.1.7 on 2023-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0002_poi_feature_poi_habitat_poi_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
