# Generated by Django 4.1.7 on 2023-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0003_poi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
