# Generated by Django 4.1.7 on 2023-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0004_alter_poi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
