# Generated by Django 4.1.7 on 2023-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0005_alter_poi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='animal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
