# Generated by Django 4.1.7 on 2023-04-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0003_poi_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiscussionApp', '0002_chatmessage_remove_discussion_poi_delete_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chatroom',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapApp.poi')),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
