# Generated by Django 4.1.7 on 2023-04-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionApp', '0002_alter_chatmessage_upvotes'),
        ('DiscussionApp', '0004_chatmessage_parentmessage_chatmessage_upvotes'),
    ]

    operations = [
    ]
