# Generated by Django 4.1.7 on 2023-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionApp', '0003_alter_chatmessage_parentmessage'),
        ('DiscussionApp', '0005_merge_20230424_1632'),
    ]

    operations = [
    ]
