# Generated by Django 4.1.7 on 2023-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionApp', '0002_alter_chatmessage_upvotes'),
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upvotedMessages',
            field=models.ManyToManyField(null=True, to='DiscussionApp.chatmessage'),
        ),
    ]
