# Generated by Django 4.1.7 on 2023-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionApp', '0007_alter_chatmessage_parentmessage'),
        ('ProfileApp', '0002_userprofile_upvotedmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='upvotedMessages',
            field=models.ManyToManyField(blank=True, null=True, to='DiscussionApp.chatmessage'),
        ),
    ]
